name: Label Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/microsoft/hve-core/refs/heads/main/.github/labels.yml
          delete-other-labels: false
          token: ${{ secrets.GITHUB_TOKEN }}
